---

- name: Get current config
  changed_when: false
  check_mode: false
  failed_when: false
  ansible.builtin.command:
    cmd: "ceph nfs export get {{ export.cluster_id }} {{ export.pseudo }}"
  register: __existing_config

- name: Set existing export fact
  ansible.builtin.set_fact:
    ceph_existing_nfs_export: "{{ __existing_config.stdout | from_json if __existing_config.stdout else {} }}"

- name: Show differences
  ansible.utils.fact_diff:
    before: "{{ ceph_existing_nfs_export }}"
    after: "{{ ceph_nfs_configured_export }}"
  register: __cfg_diff

- name: Apply export config
  ansible.builtin.command:
    cmd: "ceph nfs export apply {{ export.cluster_id }} -i -"
    stdin: "{{ ceph_nfs_configured_export | to_json }}"
  when: __cfg_diff.diff_lines
